### ISSUE TITLE
Question: route traffic through guest vm

### ISSUE THREAD

**Issue by yurks** [s-u/macosvm#23]
Is it possible to route traffic to specific subnet from host to guest vm? Let's say, we have a VPN connection in guess vm and would like to access certain vpn-subnet from host.

**Comment by s-u** [comment]
The host has no access to guest's VPN by definition (that's the point of VPNs - it's private). Presumably you could have the host connect to the same VPN as the guest, but that has really nothing to do with the virtualization but rather your VPN setup. By default (nat networking) the guest is simply connected through the host on a subnet managed by the VZ framework. What you put on top of that is entirely up to you.

**Comment by yurks** [comment]
Yes, I understand the basics, for sure I can't access guest VPN. Let me ask in another way and forget about VPN (although this question  is probably not for you, if you are not a "networking masters";)): how to correctly route some traffic from host to guest, what's the best option for that? At this point and my current knowledge I suppose I can setup guest ssh-server, connect to it from host and create some host route to that connection. But maybe there is a way without ssh?

**Comment by s-u** [comment]
The traffic from the host to guest is direct - they are on the same subnet (192.168.64.0/24) so it's all transparent. The host also does a NAT automatically, which is why the VM can access all networks that the host can (local, internet...). So can you be more clear on what exactly you are trying to do? The host can directly access the guest and vice versa - there is no routing involved.

**Comment by yurks** [comment]
I want to setup VPN inside guest, which create an interface with subnet, let's say, 10.1.2.0/24.
After that I trying route all traffic from host to address 10.1.2.3 to -> guest 192.168.64.20 and then to -> guest vpn 10.1.2.3

**Comment by s-u** [comment]
Well, once you setup the VPN it's done. Any traffic to the guest VPN IP goes through the tunnel which is transported over the 192.168.24/24 network. Thats' the point of VPN: you get

```
               host             |             guest
10.1.2.1 -> 192.168.64.1. -VPN-tunnel-> 192.168.64.20 -> 10.1.2.3
```
so what's the question?

**Comment by s-u** [comment]
Since this seem to have nothing to do with VMs nor `macosvm` and there seems nothing to solve I'm closing this.
