### ISSUE TITLE
Help screen wrong

### ISSUE THREAD

**Issue by PaoloSupino** [s-u/macosvm#27]
When running the macosvm -h it gives the following output: 
 Usage: ./macosvm [-g|--[no-]gui] [--[no-]audio]
           [--restore \<path\>] [--ephemeral] [--recovery]
           [--{disk|usb} \<path\>[,ro][,size=\<spec\>][,keep]] [--aux \<path\>]
           [--vol \<path\>[,ro][,{name=<\name\>|automount}]]
           [--net \<spec\>] [--mac \<addr\>] [-c \<cpu\>] [-m \<ram\>]
           [--no-serial] [--pty]   \<config.json\>

which indicates that the command line switch to specify the amount of RAM is '-m'. This is wrong... The command line switch to specify the amount of RAM is actually '-r' ...

**Comment by s-u** [comment]
Thanks!
