### ISSUE TITLE
running headless without a logged in user

### ISSUE THREAD

**Issue by anszom** [s-u/macosvm#33]
I've been running macosvm as a part of a DIY "github self-hosted runner" solution. It works quite well as long as the user running macosvm is logged in with a GUI session (locally or via VNC). Otherwise, macosvm gets stuck at:
```
2024-06-07 10:36:26.254 macosvm[42244:1439972]  . cloning disk.img to ephemeral disk.img-clone-42244
2024-06-07 10:36:26.256 macosvm[42244:1439972]  . cloning aux.img to ephemeral aux.img-clone-42244
```

My guess would be that NSApplication somehow gets stuck when no GUI session is available. Is there any workaround?

**Comment by s-u** [comment]
Thanks. It turns out that headless apps never gets the `applicationDidFinishLaunching:` notification, so the way to go is to use `applicationWillFinishLaunching:` instead for headless starts (i.e. those without `-g`) which seems to work.
